/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAdvancedERC20 {
  export type TokenInitStruct = {
    name: string;
    symbol: string;
    decimals: BigNumberish;
    owner: AddressLike;
    tierId: BigNumberish;
    templateVersion: BigNumberish;
  };

  export type TokenInitStructOutput = [
    name: string,
    symbol: string,
    decimals: bigint,
    owner: string,
    tierId: bigint,
    templateVersion: bigint
  ] & {
    name: string;
    symbol: string;
    decimals: bigint;
    owner: string;
    tierId: bigint;
    templateVersion: bigint;
  };

  export type FeeSplitStruct = {
    feeType: BigNumberish;
    bps: BigNumberish;
    recipient: AddressLike;
  };

  export type FeeSplitStructOutput = [
    feeType: bigint,
    bps: bigint,
    recipient: string
  ] & { feeType: bigint; bps: bigint; recipient: string };

  export type InitRecipientStruct = {
    account: AddressLike;
    amount: BigNumberish;
    vesting: boolean;
    vestingStart: BigNumberish;
    cliff: BigNumberish;
    duration: BigNumberish;
    revocable: boolean;
  };

  export type InitRecipientStructOutput = [
    account: string,
    amount: bigint,
    vesting: boolean,
    vestingStart: bigint,
    cliff: bigint,
    duration: bigint,
    revocable: boolean
  ] & {
    account: string;
    amount: bigint;
    vesting: boolean;
    vestingStart: bigint;
    cliff: bigint;
    duration: bigint;
    revocable: boolean;
  };

  export type AntiWhaleConfigStruct = {
    enabled: boolean;
    maxTxAmount: BigNumberish;
    maxWalletAmount: BigNumberish;
    cooldownBlocks: BigNumberish;
  };

  export type AntiWhaleConfigStructOutput = [
    enabled: boolean,
    maxTxAmount: bigint,
    maxWalletAmount: bigint,
    cooldownBlocks: bigint
  ] & {
    enabled: boolean;
    maxTxAmount: bigint;
    maxWalletAmount: bigint;
    cooldownBlocks: bigint;
  };

  export type TokenConfigStruct = {
    initialSupply: BigNumberish;
    cap: BigNumberish;
    mintable: boolean;
    burnable: boolean;
    pausable: boolean;
    governanceEnabled: boolean;
    autoLiquidityEnabled: boolean;
    antiWhaleEnabled: boolean;
    stakingEnabled: boolean;
    autoLiquidityBps: BigNumberish;
    autoLiquidityRouter: AddressLike;
    autoLiquidityPairToken: AddressLike;
    stakingManager: AddressLike;
    metadataURI: string;
    brandingURI: string;
    fees: IAdvancedERC20.FeeSplitStruct[];
    initialDistribution: IAdvancedERC20.InitRecipientStruct[];
    minters: AddressLike[];
    pausers: AddressLike[];
    burners: AddressLike[];
    bridgeOperators: AddressLike[];
    antiWhale: IAdvancedERC20.AntiWhaleConfigStruct;
  };

  export type TokenConfigStructOutput = [
    initialSupply: bigint,
    cap: bigint,
    mintable: boolean,
    burnable: boolean,
    pausable: boolean,
    governanceEnabled: boolean,
    autoLiquidityEnabled: boolean,
    antiWhaleEnabled: boolean,
    stakingEnabled: boolean,
    autoLiquidityBps: bigint,
    autoLiquidityRouter: string,
    autoLiquidityPairToken: string,
    stakingManager: string,
    metadataURI: string,
    brandingURI: string,
    fees: IAdvancedERC20.FeeSplitStructOutput[],
    initialDistribution: IAdvancedERC20.InitRecipientStructOutput[],
    minters: string[],
    pausers: string[],
    burners: string[],
    bridgeOperators: string[],
    antiWhale: IAdvancedERC20.AntiWhaleConfigStructOutput
  ] & {
    initialSupply: bigint;
    cap: bigint;
    mintable: boolean;
    burnable: boolean;
    pausable: boolean;
    governanceEnabled: boolean;
    autoLiquidityEnabled: boolean;
    antiWhaleEnabled: boolean;
    stakingEnabled: boolean;
    autoLiquidityBps: bigint;
    autoLiquidityRouter: string;
    autoLiquidityPairToken: string;
    stakingManager: string;
    metadataURI: string;
    brandingURI: string;
    fees: IAdvancedERC20.FeeSplitStructOutput[];
    initialDistribution: IAdvancedERC20.InitRecipientStructOutput[];
    minters: string[];
    pausers: string[];
    burners: string[];
    bridgeOperators: string[];
    antiWhale: IAdvancedERC20.AntiWhaleConfigStructOutput;
  };
}

export interface IAdvancedERC20Interface extends Interface {
  getFunction(
    nameOrSignature: "initialize" | "templateVersionConstant"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "initialize",
    values: [IAdvancedERC20.TokenInitStruct, IAdvancedERC20.TokenConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "templateVersionConstant",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "templateVersionConstant",
    data: BytesLike
  ): Result;
}

export interface IAdvancedERC20 extends BaseContract {
  connect(runner?: ContractRunner | null): IAdvancedERC20;
  waitForDeployment(): Promise<this>;

  interface: IAdvancedERC20Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  initialize: TypedContractMethod<
    [
      init: IAdvancedERC20.TokenInitStruct,
      cfg: IAdvancedERC20.TokenConfigStruct
    ],
    [void],
    "nonpayable"
  >;

  templateVersionConstant: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      init: IAdvancedERC20.TokenInitStruct,
      cfg: IAdvancedERC20.TokenConfigStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "templateVersionConstant"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
