/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDOFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "allPools" | "createPool" | "getAllPools" | "isPool"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PoolCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPools",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isPool", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "allPools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPool", data: BytesLike): Result;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    pool: AddressLike,
    saleToken: AddressLike,
    raiseToken: AddressLike
  ];
  export type OutputTuple = [
    creator: string,
    pool: string,
    saleToken: string,
    raiseToken: string
  ];
  export interface OutputObject {
    creator: string;
    pool: string;
    saleToken: string;
    raiseToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDOFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IDOFactory;
  waitForDeployment(): Promise<this>;

  interface: IDOFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allPools: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createPool: TypedContractMethod<
    [
      owner: AddressLike,
      saleToken: AddressLike,
      raiseToken: AddressLike,
      fundsRecipient: AddressLike,
      startTime: BigNumberish,
      endTime: BigNumberish,
      softCap: BigNumberish,
      hardCap: BigNumberish,
      minContribution: BigNumberish,
      maxContribution: BigNumberish,
      tokensPerUnit: BigNumberish,
      whitelistEnabled: boolean
    ],
    [string],
    "nonpayable"
  >;

  getAllPools: TypedContractMethod<[], [string[]], "view">;

  isPool: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allPools"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      saleToken: AddressLike,
      raiseToken: AddressLike,
      fundsRecipient: AddressLike,
      startTime: BigNumberish,
      endTime: BigNumberish,
      softCap: BigNumberish,
      hardCap: BigNumberish,
      minContribution: BigNumberish,
      maxContribution: BigNumberish,
      tokensPerUnit: BigNumberish,
      whitelistEnabled: boolean
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllPools"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isPool"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;

  filters: {
    "PoolCreated(address,address,address,address)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
  };
}
